### ISSUE TITLE
Bundling doesn't work properly on Windows

### ISSUE THREAD

**Issue by explorigin** [miracle2k/webassets#208]
Because Windows uses backslashes, glob gets a little confused when its trying to resolve a bundle name.  The solution is simple:

Wrap https://github.com/miracle2k/webassets/blob/master/src/webassets/env.py#L145 in os.path.normpath() call like so:

    def glob(self, basedir, expr):
        """Generator that runs when a glob expression needs to be
        resolved. Yields a list of absolute filenames.
        """
        expr = path.normpath(path.join(basedir, expr))
        for filename in glob.iglob(expr):
            if path.isdir(filename):
                continue
            yield filename

**Comment by miracle2k** [comment]
Closing for age.
