### ISSUE TITLE
sass (with compass) doesn't expire when imported file changes.

### ISSUE THREAD

**Issue by sp3c73r2038** [miracle2k/webassets#231]
Hi,

I'm using Flask with Flask-Assets and compass.

My main sass file `common.sass` looks like:

```
@import import
@import settings

// pages
@import user.index
@import repo.index
```

and using this sass asset in template as:

```
{% assets output="common.css", filters="sass",
  "sass/common.sass" %}
  <link href="{{ ASSET_URL }}" rel="stylesheet" media="screen">
{% endassets %}
```

When I changed `_repo.index.sass`, the generated common.css didn't change. But I tried to modify `common.sass` then then content is latest. (also hash changed.)

Can I disable cache / manifest ?

I've tried to turn them off by:

```
assets = flask.ext.assets.Environment(app)

assets.cache = None
assets.manifest = None
```

but didn't work.

Thanks.

**Comment by sir-dunxalot** [comment]
For anyone coming across this issue, this config solved the issue for me (it took a while to figure out the correct syntax for the `depends` option) [per these docs](http://webassets.readthedocs.io/en/latest/bundles.html):

```py
css = Bundle(
  # Paths to CSS dependencies you don't want to run through scss go here
  Bundle(
    'styles/app.scss',
    filters = 'scss',
    depends = ('**/*.scss'),
  ),
  output = 'css-dist.css'
)
```
