### ISSUE TITLE
Append Yaml syntax example in documentation with cssrewrite and replace parameter

### ISSUE THREAD

**Issue by harobed** [miracle2k/webassets#300]
I suggest to append in documentation an example to explain how to write this : 

```
get_filter('cssrewrite', replace={'old_directory':'/custom/path/'})
```

in YAML.

**Comment by miracle2k** [comment]
I don't think it is currently possible. However, the cssrewrite filter could be changed to take the "replace" setting via the configuration/environment, like most other settings currently support (that would be global, though).
