### ISSUE TITLE
Dealing with a non-writable /static directory

### ISSUE THREAD

**Issue by pwaller** [miracle2k/webassets#355]
I'm in a similar situation as #144, except I have some additional constraints.

I am running my application inside Docker, and in order to have live code reloading I want to bind mount my code inside the container (including `/static`). However, the docker container is not allowed to write there, so writing `.webassets-cache` fails. The obvious thing to do is to set the `assets.cache = '/tmp/webassets-cache'` so that webassets can write the cache, and the `assets.directory = '/tmp/webassets-directory'` so that webassets has somewhere writable it can dump the assets.

This all works, except that the webserver looks for `http://host/static/buildproduct.css` at `./static/buildproduct.css`.

For production, I'm happy to set `auto_build = False` and do the asset generation via an external script, but for development this doesn't work very well.

So the constraints are:
- Only `/tmp` is writable
- I want to serve generated and non-generated assets from `http://host/static/`

Is there a way to achieve this, and if not, can we add one?

**Comment by sealemar** [comment]
@miracle2k, thank you for the suggestion. Here is a complete snippet that worked for me.

```
assets.directory = "/tmp/webassets/static"
assets.url = "/assets-static"

from flask import send_from_directory
@app.route('/assets-static/<path:name>')
def serve_assets_static(name):
    return send_from_directory(assets.directory, name)
```
