### ISSUE TITLE
Ability to configure group permissions on .webassets-cache directory and subfiles

### ISSUE THREAD

**Issue by JDeuce** [miracle2k/webassets#371]
So I'm trying to configure an application that uses webassets so that it can be deployed by multiple Unix users, utilizing group permissions so that all changes from one user are writable by all users in the group.

Running into a roadblock with webassets, because it forces all files created in the webassets-cache directory to be created without group write or read permissions, thus if one user ends up writing a file as part of their webassets build, they will blow up the build for all other users.

I have the group sticky bit set on the webasset-cache directory, which makes all files created by default in that directory have the group read/write permissions enabled. But because of the use of mkstemp when webassets creates the file, it guarantees the group read/write bits will not be set on the resulting file. See: https://github.com/miracle2k/webassets/blob/master/src/webassets/cache.py#L202

I think the solution might be to add a new configurable in the webassets config, which specifies the permissions that you want the webassets cache files to have (default to 0600 as now), and then explicitly calling os.chmod before the rename. That way in my configuration I could set the permissions to 0660 and it'd be fine. Thoughts?

**Comment by JDeuce** [comment]
Would be nice if there was a config option where you could override the mode that it creates these files in, instead of forcing it to be created in ultra secure mode

**Comment by bcb** [comment]
+1

**Comment by iakbar** [comment]
+1

**Comment by shtr0m** [comment]
+1
