### ISSUE TITLE
RequireJS Filter modname and parameters

### ISSUE THREAD

**Issue by ornj** [miracle2k/webassets#374]
[Starting on line 158 of requirejs.py](https://github.com/miracle2k/webassets/blob/master/src/webassets/filter/requirejs.py#L158), the RequireJS filter is attempting to infer the AMD module name.

```py
        # extract the AMD module name
        name = kw.get('source')
        if not name:
            # ...
        kw['modname'] = path.splitext(name)[0]
```

The result of this is not guaranteed to be accurate. It would depend on how you've structured your project. Unless I'm missing something, this module name is not likely to be correct unless your Javascript application's point of entry is a top level module in `static`.

Say for example the structure of your static directory looked like mine often do:

```
/static
    /js
        /main.js
        /config.js
        /build.js
    /vendor
        /underscore
        /etc
```

The point of entry (main.js) would be interpreted to be `js/main` where as you may have intended `./js` to be the `baseUrl` causing builds to fail, unless you prepended all your module names with `js/`. Since command line parameters are being assigned by the filter, the user cannot override these values as RequireJS gives precedence to command line parameters over the build profile. 

It would be nice to be able to omit parameters passed to r.js in favor of values set in a build profile, but in this situation  it is possible to "adjust" for the filter's command line parameters through the build profile. You can correct the module names / paths to be relative to the `/js` directory which would make the above directory structure work.

```js
({
    paths: {
        'js': './'
        'underscore': '../vendor/underscore/underscore'
    }
})
```

**Comment by andresmrm** [comment]
I'm having the same problem here...
@ornj did you manage to solve it?

**Comment by ornj** [comment]
@andresmrm Just what I outlined above.

**Comment by andresmrm** [comment]
Thanks for the answer, @ornj .
But, sorry, I still don't understand.

You mean you "prepended all your module names with `js/`"? Or used a "build profile"?
The first one seems too bad, for it won't work without webassets. The second seems better, if it's possible to use a build profile without replicating all the info from the config file. But then, how do I use the build profile with the config file?

I have a directory structure similar to the one you showed, but with some files in a `app` folder:

    /static
        /js
            /app
                /main.js
                /one.js
                /two.js
            /config.js
            /build.js

I'm using:

    REQUIREJS_EXTRAS = "mainConfigFile=static/js/config.js include=requirejs"

and:

    requirejs = Bundle('js/build.js',
                    filters='requirejs',
                    output='gen/packed.js',
                    depends="js/app/*")

Should I set `REQUIREJS_BASEURL = "static/js"`?

I tried many combinations for all the configs, but always getting a "no such file" `static/app/main.js` or `static/js/js/build.js` or...
Thanks for any help.

**Comment by ornj** [comment]
I mean the second option.

It's annoying to have duplicate configurations for r.js and the browser config. It's a lingering annoyance that requirejs hasn't been able to adequately solve, but look at it this way. You can spend all day trying to solve it or just duplicate the config and be done with it. It feels gross but you'll get over it.

You shouldn't need to use `REQUIREJS_EXTRAS` to provide a build profile. Here's my config:

```
REQUIREJS_BASEURL = 'app/static/js'
REQUIREJS_CONFIG = 'js/build.js'
REQUIREJS_RUN_IN_DEBUG = False
```

If you're nesting your files under an `app/` directory then alter paths accordingly.

Also, take a look at that "no such file" error you are getting. I've found that depending on how my project is set up, some times the node executable isn't found and you'll get that message. Usually when the r.js executable cannot find a file it's pretty explicit as to what it can't find.

It can be helpful to print out the exact command the filter is attempting to run and then run it yourself manually. You'll be able to spot any issues and correct your input.

**Comment by andresmrm** [comment]
Tried using only `build.js`. Now I get this error:

    Error: If the "modules" option is used, then there should be a "dir" option set and "out" should not be used since "out" is only for single file optimization output.

If I set `dir` in `build.js`, another error:

    Error: The "out" and "dir" options are incompatible. Use "out" if you are targeting a single file for optimization, and "dir" if you want the appDir or baseUrl directories optimized.

**Comment by ornj** [comment]
This is more about RequireJS and not so much Webassets. The errors are pretty explicit as to what is incorrect. 

I'm going to refer you to the [RequireJS optimization documentation](http://requirejs.org/docs/optimization.html) from here..

**Comment by andresmrm** [comment]
But I'm not setting `out`... It seems to be set by Webassets...
I tried not to set the `output` from `Bundle`, but then I get a Webassets error.

**Comment by ornj** [comment]
https://github.com/miracle2k/webassets/blob/master/src/webassets/filter/requirejs.py#L144

**Comment by andresmrm** [comment]
Using `r.js` directly, this seems to work here:

    r.js -o static/js/build.js

build.js:

    ({
        baseUrl: ".",
        dir: "../../appdirectory-build",
        mainConfigFile: "config.js",
        modules: [
            {
                name: "app/main"
            }
        ]
    })

So it's not even needed to replicated `config.js` inside `build.js`.

The problem is Webassets is enforcing the `out` option, has @ornj pointed me to:
https://github.com/miracle2k/webassets/blob/master/src/webassets/filter/requirejs.py#L144
And by doing this it seems to disable a whole project build in **r.js**.

(If the Bundle has no `output` or it's `None` or `"null"`, it raises `BuildError('No output target found for %s' % self)`, so it's not a solution.)

So, it seems to me that the `out` option needs to be made optional somehow for a whole build to work.
