### ISSUE TITLE
UglifyJS and --source-map

### ISSUE THREAD

**Issue by shahafabileah** [miracle2k/webassets#379]
I'd like to produce minified JS code and to have corresponding source maps.  My goal is to have readable stacktraces in production (https://rollbar.com/docs/source-maps/).

It looks like UglifyJS supports source maps, so I'm trying to use that filter.

My setup is like this:
```
    env.config['UGLIFYJS_BIN'] = './node_modules/uglify-js/bin/uglifyjs'
    env.config['UGLIFYJS_EXTRA_ARGS'] = ['--source-map', 'my_source_map.txt', '-c', '-m', '--lint']
```

But when I run this, I get an error:
```
FilterError: uglifyjs: subprocess returned a non-success result code: 1, stdout=, stderr=ERROR: Source map doesn't work with input from STDIN
```

It looks like it originates here: https://github.com/mishoo/UglifyJS2/blob/master/bin/uglifyjs#L219

Is there a known workaround?

Also, in my project I actually have multiple JS bundles: common.min.js, home.min.js, etc.  I'd like to generate a corresponding source map for each one.  But as written above, I have a single hard-coded file name for the source map in UGLIFY_EXTRA_ARGS.  That same value will be used for each bundle.  Is there a way for me to dynamically choose a matching name?  e.g. common.min.js.map, home.min.js.map

Moreover, I'm using the cache-busting mechanism, so my files are really common.<hash>.min.js, home.<hash>.min.js, etc.  I'd like the corresponding maps to also have the hash, to avoid loading a stale map.  Is it possible to dynamically choose a matching name with-hash?

Thanks!

--S

**Comment by miracle2k** [comment]
1. The stdin issue. You will probably have to modify the filter (a patch is welcome). Ideally you can provide the actual filename as an additional option; uglifyjs really should support sommething like this; Or the filter would have to be rewritten to work as an open filter (meaning: the first filter applied; then, you can give the original file directly to uglifyjs, rather than an stdin object).

2. The source map path setting: If you instantiate the filters manually, you can provide specific options:

    from webassets.filters.uglifyjs import UglifyJS
    Bundle(filters=[UglifyJS(extra_args=[])])

Further, you should be able to apply custom settings on a per-bundle basis as well:

    Bundle(config={'UGLIFYJS_EXTRA_ARGS={}})

3. As for hashing the source map filename, I am at a loss. I doubt its possible; The hash used is the has of the file contents; the file contents cannot then reference the sourcemap containing the final hash.

**Comment by shahafabileah** [comment]
Thanks for the quick response!

I tried using a different JS minifier: Closure.  It also supports source maps and it has no qualms about taking the raw JS from stdin.

However, the source map it produces with webassets looks like this:
```
{
    ...
    "sources":["stdin"],
    ...
}
```

By contrast, if I run closure from the command line and specify each JS file separately, then they get included in the map:
```
> venv/bin/closure --js static/js/account.js --js static/js/dialog.js --compilation_level SIMPLE_OPTIMIZATIONS --create_source_map test.map
...

> more test.map
{
    ...
    "sources":["static/js/account.js","static/js/dialog.js"],
    ...
}
```

I worry that the stdin approach defeats the purpose of having a source map in the first place.  The whole point is for the source map to help us identify the original filename.  But if the source map only has "stdin" then it can't tell us where to look.

Does this mean that we would need to switch away from a stdin-based approach in order to generate a complete source map?  If so, can we do it with webassets?

---

Other thoughts...

I took your suggestion of manually constructing the filter object (instead of just providing the class name) in order to specify custom arguments:

```
BEFORE

    def js_bundle(name, *files):
        bundle = Bundle(
            *files,
            filters = ('closure_js',),
            output = name + '.%(version)s.gen.js')
        assets.register(name + '_js', bundle)

AFTER

    def get_js_filter(name):
        return ClosureJS(opt='SIMPLE_OPTIMIZATIONS', extra_args=['--create_source_map', 'my/path/' + name + '.min.js.map'])

    def js_bundle(name, *files):
        bundle = Bundle(
            *files,
            filters = [get_js_filter(name)],
            output = name + '.%(version)s.gen.js')
        assets.register(name + '_js', bundle)
```

This worked like a charm.

I take your point that it's impossible to know the minified file's hash before the file is generated!  :-)  Instead, I'm looking into using my git commit hash as the cache-busting token.

I burned a bunch of time trying to figure out why the following output() function was not getting called:

```
class ClosureJS(JavaTool):
    ...
    def output(self, _in, out, **kw):
        import pdb; pdb.set_trace() # <-- I added this locally, but it was never hit
        ...
```

In the end I discovered that this was a caching issue.  There's a .webassets-cache directory and it already had the minified code, so there was no need to actually run the minifier again.

But there may be a problem here.  The issue is that when I first ran the filter, I didn't have the `--create_source_map` option.  Then I added the source map option and tried to run webassets again, but it didn't seem to take effect.  It appears that webassets still used the value from the cache and it skipped actually running the filter.  So I would get the minified JS file back, but I still wouldn't get a source map file.

I think it might be appropriate to revise the webassets-cache keys to also include all filter parameters.  So, if I run the same filter a second time but with different arguments, webassets shouldn't use the cached result.

**Comment by shahafabileah** [comment]
...and I just reread your original comment:

> Or the filter would have to be rewritten to work as an open filter (meaning: the first filter applied; then, you can give the original file directly to uglifyjs, rather than an stdin object).

I gather that you are referring to this:

```
class Filter(object):
    ...
    def open(self, out, source_path, **kw):
        """Implement your actual filter here.

        This is like input(), but only one filter may provide this.
        Use this if your filter needs to read from the source file
        directly, and would ignore any processing by earlier filters.
        """
```

OK.  I'll look into writing a new version of the ClosureJS class that works with open() instead of input().  This is all unfamiliar code, so if there's anything special I need to know, do share.

And please let me know what you think about the caching issue I noted before.

**Comment by aconrad** [comment]
Keep posting your findings here @shahafabileah as I've also been trying to generate source maps but never got the time to look into it deeply. Thanks!

**Comment by miracle2k** [comment]
Regarding stdin and source maps, I really don't know. When using a very modern tool like gulp, it is not uncommon that I may apply multiple transforms, maybe an es6 transpiler, and still I get sourcemaps. I never used source maps with webassets, I don't know what closure or uglify supports that could be used.

The cache key issue is known to me, and there is probably a TODO along those lines, too. Yes, filter options should be part of the key.

**Comment by shahafabileah** [comment]
I wrote a rough version of a ClosureJS filter that supports source maps.  It's included below.  As you suggested, it uses the open() method instead of output().  And it does successfully generate a source map file with an actual source JS file name (instead of "input").  The trouble is that the open() method is called for each JS file in the bundle separately.  So, instead of a single source map that lists all source JS files, we end up with N source maps, one for each file.  In other words, it's not really a solution yet.

Here's the revised filter:
```
'''
This is an alternate implementation of the ClosureJS filter for webassets.
The goal is to support source maps.  To do that, this version uses the
open() method instead of the more typical output() method.  As a
consequence, this version can only be used as the first filter in the
chain.

See https://github.com/miracle2k/webassets/issues/379
'''

from __future__ import absolute_import
from webassets.filter import JavaTool


__all__ = ('ClosureJSWithSourceMaps',)

class ClosureJSWithSourceMaps(JavaTool):

    name = 'closure_js_with_source_maps'
    options = {
        'opt': 'CLOSURE_COMPRESSOR_OPTIMIZATION',
        'extra_args': 'CLOSURE_EXTRA_ARGS',
    }

    # In order to get access to the original files, we must declare
    # that this filter uses the open() method.
    method = 'open'

    def setup(self):
        super(ClosureJSWithSourceMaps, self).setup()

        try:
            self.jar = self.get_config('CLOSURE_COMPRESSOR_PATH',
                                       what='Google Closure Compiler')
        except EnvironmentError:
            try:
                import closure
                self.jar = closure.get_jar_filename()
            except ImportError:
                raise EnvironmentError(
                    "\nClosure Compiler jar can't be found."
                    "\nPlease either install the closure package:"
                    "\n\n    pip install closure\n"
                    "\nor provide a CLOSURE_COMPRESSOR_PATH setting "
                    "or an environment variable with the full path to "
                    "the Closure compiler jar."
                )

    def open(self, out, source_path, **kw):
        args = ['--js', source_path, # <--- ideally we would specify ALL source paths here
                '--charset', 'UTF-8',
                '--compilation_level', self.opt or 'WHITESPACE_ONLY']
        if self.extra_args:
            args.extend(self.extra_args)
        self.subprocess(args, out)
```

And here's how I use it:
```
from lib.closure_js_filter import ClosureJSWithSourceMaps

def get_js_filter(bundle_name):
    source_map_file = 'static/gen/' + bundle_name + '.gen.js.map'
    js_filter = ClosureJSWithSourceMaps(opt='SIMPLE_OPTIMIZATIONS', extra_args=['--create_source_map', source_map_file])
    return js_filter

def js_bundle(name, *files):
    bundle = Bundle(
        *files,
        filters = [get_js_filter(name)],
        output = name + '.%(version)s.gen.js')
    assets.register(name + '_js', bundle)

js_bundle('common', 'foo.js', 'bar.js', ...)

js_bundle('home', 'wesley.js', 'buttercup.js', ...)
```

Note this line in the filter code:
```
        args = ['--js', source_path, # <--- ideally we would specify ALL source paths here
```

When you call the closure compiler on the commandline, you CAN specify multiple JS files...

```
> venv/bin/closure --js foo.js --js bar.js ... --charset UTF-8 --compilation_level SIMPLE_OPTIMIZATIONS --create_source_map static/gen/common.gen.js.map
```

It would be sweet if I could construct a command like this, with multiple JS files.  But I don't know how to do that.  In the output() method I'm only told about ONE of the JS files at a time.  Is there some other approach I can take that would provide the full list of JS files?

Thanks!

--S
