### ISSUE TITLE
relative imports don't work with Sass/SCSS

### ISSUE THREAD

**Issue by aconrad** [miracle2k/webassets#383]
Webassets compiles SCSS by reading SCSS files and passing them to Sass via stdin (`--stdin` flag) and may cause applications to not work (even though they did before switching to webassets) if import statements are relative to the source file:

```
Traceback (most recent call last):
...
webassets.exceptions.FilterError: sass: subprocess had error: stderr=(sass):1: File to import not found or unreadable: bat. (Sass::SyntaxError)
       Load paths:
         /path/to/project-foo
        on line 1 of standard input
  Use --trace for backtrace.
, stdout=, returncode=65
```

For example, if a file `foo/bar/baz.scss` imports file `foo/bar/bat.scss` (same directory) and the import is defined as `@import "bat";` then Sass will fail compiling because baz.scss is passed as stdin to Sass and Sass has naturally no information on where baz.scss is located on disk. To overcome this issue, the full path must be provided in the import statement: `@import "foo/bar/bat"` and Sass will use the load paths (`-I` flags) provided by webassets, in this example `-I /path/to/project-foo`, to resolve the full path: `/path/to/project-foo/foo/bar/bat.scss`.

This issue took me a lot of time to figure out since the application was working just fine before switching it to webassets, should we put a note/warning somewhere in the docs? Any pointers on where the most appropriate location would be and I'll submit a PR.

This ticket was also create so people may stumble on it if they run into the same issue as I did.

**Comment by aconrad** [comment]
It would also be nice if the original filename was reported by webassets since `on line 1 of standard input` is not very helpful with you have hundreds of assets to compile. Maybe the MemoryHunk object could take an extra attribute `.source` or something that would hold the original filename used to populate the data.

That being said, because multiple filers can be piped together, maybe it's not that easy to achieve since I'm guessing that MemoryHunk could have been populated from another MemoryHunk that concatenates a bunch of files, thus making the original filename irrelevant.

**Comment by miracle2k** [comment]
Good points and explanation. If there was a way to fix this, it would be great.

As for noting this in the documentation, I would probably put it in the sass filter docstring (which gets then pulled into the docs).
