### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by delijati** [miracle2k/webassets#386]
Sorry if this sounds like nagging but could you please release the current github version? There are several fixes that are more than a 1/2 year old (e.g. #343).

To fasten up this process i personally use `zest.releaser` or `jarn.mkrelease`.

**Comment by delijati** [comment]
Status

**Comment by r4ts0n** [comment]
I am wondering the status of project too.
Is it still active developed and maintained?

It would be sad if this good project is abandoned :(

**Comment by delijati** [comment]
It would be nice to have a "collective" like Plones https://github.com/collective for Flask it would make contributing so much easier.

**Comment by JDeuce** [comment]
Status?

**Comment by aconrad** [comment]
Would love to see this happening.

**Comment by miracle2k** [comment]
Will be upcoming.
