### ISSUE TITLE
version control of images and font files

### ISSUE THREAD

**Issue by wingyiu** [miracle2k/webassets#388]
I am looking for solutions to replace the url in css file ,such as `background:url(../a.png)` to something like `background:url(../a_acefe50.png)`, which `acefe50 ` is the hash of a.png。

is it possible to archive this using webassets.

![](http://pic3.zhimg.com/edf10bb428d39d721e36760a86d2641e_r.jpg)

**Comment by miracle2k** [comment]
Not currently, no.
