### ISSUE TITLE
Per-Bundle auto_build property

### ISSUE THREAD

**Issue by aluuu** [miracle2k/webassets#389]
Hello.

It would be great if it was possible to specify `auto_build` property on some `Bundle`s instead of doing it for the whole `Environment`.

What do you think about it?

**Comment by miracle2k** [comment]
It's kind of a hidden feature, but I think it should work if you use ``Bundle.config``, i.e. ``Bundle.config.auto_build = True``

**Comment by aluuu** [comment]
Ok. I'll try to implement this feature if you don't mind.

**Comment by miracle2k** [comment]
It should be implemented, try the lines I gave you above.
