### ISSUE TITLE
UnicodeDecodeError on building assets (Continuation of #225)

### ISSUE THREAD

**Issue by kageurufu** [miracle2k/webassets#395]
I am getting another UnicodeDecodeError when building an asset that contains the MIDDLE_DOT codepoint (`·`, http://www.fileformat.info/info/unicode/char/b7/index.htm)

The source file in question is from [jquery.smartbanner.js](https://github.com/jasny/jquery.smartbanner/blob/master/jquery.smartbanner.js)

**Comment by miracle2k** [comment]
I stack trace would be useful, but basically, webassets opens all input files as utf-8 right now, so as long as all source files load as utf8, there shouldn't be any problems.

**Comment by kageurufu** [comment]
I finally found the source of this issue, sorry about the long delay

It looks when using a URL source, urlopen in the UrlHunk doesn't parse the Content-Type header and decodes as ASCII, not UTF-8.

Using webassets==0.12.0:

```python
>>> from webassets.merge import UrlHunk
>>> hunk = UrlHunk('http://cdn.rawgit.com/novus/nvd3/v1.8.1/build/nv.d3.min.js')
>>> type(hunk.data())
<type 'str'>
>>> u'±' in hunk.data().decode('utf-8')
True
```
