### ISSUE TITLE
CSS minification with cssmin breaks calc()

### ISSUE THREAD

**Issue by Markus00000** [miracle2k/webassets#397]
Input:

    padding: calc(1rem + 4px);

Minified output using `cssmin`:

    padding:calc(1rem+4px);

The minified calculation is broken as:

> The + and - operators must always be surrounded by whitespace.

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/calc

Expected minified output:

    padding:calc(1rem + 4px);

**Comment by miracle2k** [comment]
This seems like a bug in the cssmin package, which is not shipped with webassets.

**Comment by Markus00000** [comment]
You are correct: https://github.com/zacharyvoase/cssmin/issues/16

Adding a note to the docs that `cssmin` is no longer maintained and has open issues would be helpful. It's the first entry under CSS compressors and others might pick it blindly like I did instead of comparing the five compressors.

**Comment by kristianroebuck** [comment]
If you're using cssmin and want to get around this issue without having to switch to another minifier you're able to change your CSS from this:

`width: calc(100% + 2px);`

to this:

`width: calc(100% - -2px);`

Not ideal, but it works.

**Comment by patrickyan** [comment]
Can you switch cssmin to something that actually works?
