### ISSUE TITLE
No CLEANCSS_EXTRA_ARGS in latest version?

### ISSUE THREAD

**Issue by brendansudol** [miracle2k/webassets#410]
Pardon this noob question - I see from this (merged) pull request (https://github.com/miracle2k/webassets/pull/377) that CLEANCSS_EXTRA_ARGS was to cleancss.py. My question is why isn't this propagated to the latest releases which have come after that? Is there another version I should be using in my requirements.txt so I have access to this?

Many thanks

**Comment by miracle2k** [comment]
There hasn't been a new release in a while; it's probably time for one.

**Comment by brendansudol** [comment]
cool - appreciate it!
