### ISSUE TITLE
Compass filter broken in 0.11

### ISSUE THREAD

**Issue by tilgovi** [miracle2k/webassets#415]
In line 206, `config.to_string()` returns a string on Python 2 and it needs to be a unicode object now that `io.open` is being used.

**Comment by tilgovi** [comment]
I was going to make a PR. I'm thinking that making `to_string()` return `u"\n".join(...)` would be sufficient, but just in case the right fix is something less intuitive, like opening the config file in binary mode, I thought I'd simply file the issue. Might be good to release a 0.11.1 with this fix since it renders compass unusable. :-/

**Comment by miracle2k** [comment]
I PR would be welcome, I think the solution you suggest is fine. 

It's unfortunate that the tests didn't cache this, but I'm having a lot of trouble getting the ruby stuff to run on Travis.

**Comment by scorphus** [comment]
Is that PR on the way? If not, I'm willing to fix it (my build is badly broken) and submit a PR.

**Comment by tilgovi** [comment]
Don't wait if you want to take it! I don't be able to until tomorrow or
Monday.

**Comment by scorphus** [comment]
Well. I fixed it on my fork – as referenced above – and used that on my setup/build. I can open a PR but just want to make sure some parts of `string_rep` still make sense. I'll open a PR as soon as I'm done. Thank you :+1:

**Comment by tilgovi** [comment]
Thanks, you two.

**Comment by tilgovi** [comment]
@miracle2k any other nasty things pop up in the release that you'd like help fixing so you can get 0.11.1 out the door?
