### ISSUE TITLE
problems with django & jinja

### ISSUE THREAD

**Issue by bastianh** [miracle2k/webassets#419]
Hi,

I have used webassets successfully with flask, and now with django and django templates.
Now I tried to use jinja templates in django and I get following error:
"No assets environment configured in Jinja2 environment"
I have tried with the django integrated jinja2 template rendering and using django_jinja by adding the webassets jinja extension like described in the documentations, but I don't see any hint how to set the environment or what else is necessary to get it running.

Any help would be apreciated.

Bastian

**Comment by miracle2k** [comment]
The Jinja2 environment needs to have an attribute ``assets_enironment``:

http://webassets.readthedocs.org/en/latest/integration/jinja2.html#setting-up-the-extension
