### ISSUE TITLE
Add support for rcssmin compression filter

### ISSUE THREAD

**Issue by florianjacob** [miracle2k/webassets#424]
[rcssmin](https://github.com/ndparker/rcssmin) seems like a nice, fast and maintained alternative to the unmaintained [cssmin](https://github.com/zacharyvoase/cssmin).

Maybe a candidate for the `easy` tag for beginners?

**Comment by chris-erickson** [comment]
This is addressed now, but requires pointing pip at the repo.  @miracle2k any chance we could get a new pypi release cut?  The docs currently reference features that aren't 'available' yet.

**Comment by Oisins** [comment]
Has this been added yet?

**Comment by YuriHeupa** [comment]
No, it's pending a release with the fix, for those who need to use webassets in Python3.7 immediately, here's a workaround:

`$ pip install git+https://github.com/miracle2k/webassets`

This command will install the GitHub's latest version instead of PyPI's v0.12.1.

**Comment by miracle2k** [comment]
No new release is out yet, but I will close this ticket since it's fixed in master.
