### ISSUE TITLE
Cache issue with different files with identical content

### ISSUE THREAD

**Issue by sevens** [miracle2k/webassets#431]
I have a few SCSS files for different themes where each file only includes the `variables.scss` for that theme (defining the theme's colors) and a generic base file for processing these variables.  E.g.:
* blue/foo.scss:
```scss
@import 'variables.scss';
@import '/_base/foo.scss';
```
* black/foo.scss:
```scss
@import 'variables.scss';
@import '/_base/foo.scss';
```

Since the theme-specific `variables.scss` files are different, the expected output for the files is different.  But as the actual contents of these files are the same, the output is only generated (using normal caching options, though `environment.debug` is `True`) for the file that happens to first get requested and when the second file is requested, a separate output file is generated for it but it gets the contents of the first file.

After a bit of debugging it seems like this is due to `webassets.cache.make_md5` only looking at the actual file content when generating the MD5 for a `BaseHunk` object, which is obviously the same for both of these files.  I did a quick test with also taking the hunk's filename into account and that seems to fix the issue, at least for me.  I.e. I changed the handling code for `BaseHunk` to:
```python
        elif isinstance(obj, BaseHunk):
            # NOTE: content may be the same but final output needn't be, e.g. different
            #       search paths or 2 separate files with identical content (but relative
            #       @imports resolving to different files).
            yield obj.filename
            yield obj.data().encode('utf-8')
```

Using version 0.11.1

**Comment by miracle2k** [comment]
Have a look at the ``Bundle.depends`` attribute. If you make sure ``variables.scss``is included there, does this make a difference? I'm not sure if ``depends`` also affects the cache, or only the timestamp checking.

**Comment by sevens** [comment]
Hi miracle2k, thanks for the response.  I just tested and using `depends` (and disabling my workaround) fixes it too.  According to the docs though "Currently, using `depends` disables caching for a bundle." so maybe that's why?

**Comment by miracle2k** [comment]
Yeah, this was probably the solution for this and related issues - instead of trying to consider all dependent files in the cache key, we disable the cache completely.
