### ISSUE TITLE
Tests seems to fail on python3.5

### ISSUE THREAD

**Issue by thatguyatgithub** [miracle2k/webassets#439]
Hi there.

I was building latest webassets release for Debian and I notice that tests are failing on py3.5 with py3-test 2.8.5, which seems to be related to ever lastly encoding nightmare.

Do you mind checking? 

==================== 237 passed, 67 skipped in 3.65 seconds ====================
I: pybuild base:184: cd /build/webassets-0.11/.pybuild/pythonX.Y_3.5/build; python3.5 -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.5.1, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /build/webassets-0.11, inifile: 
collected 304 items

tests/test_bundle_build.py ......................................
tests/test_bundle_urls.py .......................
tests/test_bundle_various.py ............................s..........
tests/test_cache.py ...........
tests/test_environment.py ...............
tests/test_filters.py ...............F....ssssssssssssFsssss..ssss..sss.........ssssssssssssssssssssss...................sssssssssss
tests/test_loaders.py sssssss...
tests/test_script.py ...............s.
tests/test_updaters.py ...............
tests/test_version.py ...............
tests/test_ext/test_jinja2.py ...........

=================================== FAILURES ===================================
____________________ TestExternalToolClass.test_output_var _____________________

self = <tests.test_filters.TestExternalToolClass object at 0x7f87a0bf1748>

```
def test_output_var(self):
    class Filter(ExternalTool): pass
    self.popen.return_value.returncode = 0
    self.popen.return_value.communicate.return_value = ['stdout', 'stderr']

    # {output} creates an output file
    intercepted = {}
    def fake_output_file(argv,  **kw):
        intercepted['filename'] = argv[0]
        with open(argv[0], 'w') as f:
            f.write('bat\xf1')
        return DEFAULT
    self.popen.side_effect = fake_output_file
    # We get the result we generated in the hook above
    out = StringIO(u'')
```

> ```
>   Filter.subprocess(['{output}'], out)
> ```

tests/test_filters.py:350: 

---

webassets/filter/**init**.py:514: in subprocess
    shell=os.name == 'nt')
/usr/lib/python3/dist-packages/mock/mock.py:1062: in **call**
    return _mock_self._mock_call(_args, *_kwargs)
/usr/lib/python3/dist-packages/mock/mock.py:1128: in _mock_call
    ret_val = effect(_args, *_kwargs)

---

argv = ['/tmp/tmplpn4sbb6']
kw = {'shell': False, 'stderr': -1, 'stdin': -1, 'stdout': -1}
f = <_io.TextIOWrapper name='/tmp/tmplpn4sbb6' mode='w' encoding='ANSI_X3.4-1968'>

```
def fake_output_file(argv,  **kw):
    intercepted['filename'] = argv[0]
    with open(argv[0], 'w') as f:
```

> ```
>       f.write('bat\xf1')
> ```
> 
> E           UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 3: ordinal not in range(128)

tests/test_filters.py:345: UnicodeEncodeError
_______________________ TestBuiltinFilters.test_jspacker _______________________

self = <tests.test_filters.TestBuiltinFilters object at 0x7f87a0b0d9e8>

```
def test_jspacker(self):
    self.mkbundle('foo.js', filters='jspacker', output='out.js').build()
```

> ```
>   assert self.get('out.js').startswith('eval(function(p,a,c,k,e,d)')
> ```

tests/test_filters.py:567: 

---

webassets/test.py:88: in get
    r = f.read()

---

self = <encodings.ascii.IncrementalDecoder object at 0x7f87a033d5f8>
input = b'eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toS...|document|dummy|foo|function|\xc3\x9cnic\xc3\xb2de|s\xc3\xb3me||w\xc3\xadth|C\xc3\xb4mment|var\'.split(\'|\'),0,{}))\n'
final = True

```
def decode(self, input, final=False):
```

> ```
>   return codecs.ascii_decode(input, self.errors)[0]
> ```
> 
> E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 488: ordinal not in range(128)

/usr/lib/python3.5/encodings/ascii.py:26: UnicodeDecodeError
=============== 2 failed, 236 passed, 66 skipped in 3.87 seconds ===============

**Comment by philipithomas** [comment]
Looking at the `.travis.yml` - it doesn't look like python 3.5 is being tested:

https://github.com/miracle2k/webassets/blob/master/.travis.yml#L2
