### ISSUE TITLE
Avoid to compile CSS and JS on production?

### ISSUE THREAD

**Issue by david-xie** [miracle2k/webassets#455]
Hi,

I cannot find a place to ask question, so here I am.

Based on my understanding, webassets should be using during development and deployment, for production, we should already get all compiled CSS and JS files to use. My point is, we should avoid to compile them in production, right?

However, from what I can see, it still tries compile things. I tried to set `DEBUG` to `False`, which is not helping. BTW, I am using flask-assets for it.

What should I do then? Disable `auto-build`?

**Comment by miracle2k** [comment]
``AUTO_BUILD=False`` is recommended in production. With this enabled, the filesystem is not touched at all, and it will just generate the urls.

**Comment by david-xie** [comment]
@miracle2k Thanks!
will try this

**Comment by david-xie** [comment]
Actually, if we really wants to make it runnable without any issue, we need to add more configurations like:

```
DEBUG = False
AUTO_BUILD = False
CACHE = False
MANIFEST = False
```
