### ISSUE TITLE
Unable to use Babel filter

### ISSUE THREAD

**Issue by mivade** [miracle2k/webassets#462]
I am considering using webassets, so started writing a small demo app. I would like to be able to use ES6, so tried following the documentation example. There was the first problem: the sample code in the docs include the line:

```
es2015 = get_filter('babel', presets='es2015')
```

without actually demonstrating where to import `get_filter` from. This is easy enough to find (`from webassets.filter import get_filter`), but then when I go to run my app, I get the following error:

```
ValueError: No filter 'babel'
```

OK, fine. I guess that's because the last release on PyPI doesn't incorporate #452  yet. Here is the second problem: there really should be a new release on PyPI! But I'll try what the README says and install the development version, which brings us to problem 3:

```
$ pip install --upgrade webassets==dev
Collecting webassets==dev
  Could not find a version that satisfies the requirement webassets==dev (from versions: 0.4, 0.5, 0.6, 0.7, 0.7.1, 0.8, 0.9, 0.10, 0.10.1, 0.11, 0.11.1)
No matching distribution found for webassets==dev
```

**Comment by miracle2k** [comment]
I agree there should be a new release.

Installing ``webassets==dev``doesn't work anymore, nor will it in the future. pip doesn't support this anymore. You will need to do a "pip install http://github.com...../tar.gz", using the download url you can find on this repo.
