### ISSUE TITLE
jinja2 template-filter returns empty ASSET_URL

### ISSUE THREAD

**Issue by timesqueezer** [miracle2k/webassets#477]
Only happens with the new jinja2>=2.9.
I think it has something to do with these changes: (Quoting the changelog)

> Greatly changed the scoping system to be more consistent with what template designers and developers expect. There is now no more magic difference between the different include and import constructs. Context is now always propagated the same way. The only remaining differences is the defaults for with context and without context.

**Comment by mitsuhiko** [comment]
From a quick look at it, the current code passes the name arguments to `CallBlock` with a `store` context. That seems very wrong and if that worked before, then just by accident.

**Comment by mitsuhiko** [comment]
Affected lines of code are here: https://github.com/miracle2k/webassets/blob/c129e40beb05721bc2921b5085c23f3897464a36/src/webassets/ext/jinja2.py#L144-L145

**Comment by mitsuhiko** [comment]
BTW for 2.10 you will be able to do what the comment laments about. However the performance of that might not be particularly nice yet. This would require some investigation.

https://github.com/pallets/jinja/commit/6173cf6fc2a86f7093f4b6911b0fb3ceb30db152

**Comment by miracle2k** [comment]
@mitsuhiko Thanks for pointing out the underlying issue and the fix, it would have taken me forever to figure out how to fix it.
