### ISSUE TITLE
Testsuite seems to be broken

### ISSUE THREAD

**Issue by agustinhenze** [miracle2k/webassets#509]
Just reporting that unittests are not passing. It seems to be broken in the setup stage.

Thanks,

**Comment by moggers87** [comment]
The output from travis is:

```
cmdargs: ['/home/travis/build/miracle2k/webassets/.tox/py34/bin/pip', 'install', '--allow-all-external', '--pre', '-r/home/travis/build/miracle2k/webassets/requirements-dev.pip']
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...
no such option: --allow-all-external
```

**Comment by moggers87** [comment]
According to release notes of previous versions, this flag was a no-op anyway so it can be safely removed: https://pip.pypa.io/en/stable/news/#id44

**Comment by moggers87** [comment]
Opened PR #510 however, this just reveals more errors.

**Comment by miracle2k** [comment]
I am aware it is broken; there were too many issues with Travis over the years. Would definitely merge a PR fixing them.
