### ISSUE TITLE
jsmin/rjsmin removes blanks in ES6 Template Strings

### ISSUE THREAD

**Issue by devop911** [miracle2k/webassets#511]
Hello, i come up with an issue, which i don't know is related to webasset in detail.

I am using the rsjmin/jsmin included filter which will carry out the spaces(blank) in my ES6 js files.

as an Example:

const world = 'world';
console.log(`Hello ${world}`);

Will printed out to:

>helloworld

Is there any possible fix or configuration to use the filters with my template string?

Thank you in advance.

**Comment by 1oglop1** [comment]
@devop911 I just run into same issue, this seems to be partially fixed in `rjsmin 1.1.0` however, there is a still problem with spaces preserved inside templates.

(PS. your wrap your example into triple backticks ``` to render correctly)

I filed an issue here: ndparker/rjsmin/issues/18
