### ISSUE TITLE
Fail when packing an external resource

### ISSUE THREAD

**Issue by golyalpha** [miracle2k/webassets#512]
When trying to pack an external resource (i.e., resource not hosted on the same file system), webassets tries to cope, but eventually fails with:
`TypeError: sequence item 0: expected str instance, bytes found`

Full traceback of the issue can be found [here](https://github.com/miracle2k/flask-assets/files/2518523/traceback.txt)

**Comment by DavidLemayian** [comment]
Experienced this same issue. Thank you so much @golyalpha for pointing out! Was about to pull my hair out.

Workaround for anyone who come across the same issue: download the file to a local directory.

To note: remote file downloads seems to have used to work before but doesn't in latest `0.12.1` version. 🤔

**Comment by golyalpha** [comment]
@DavidLemayian Do you know what release were they working on?

**Comment by louking** [comment]
This seems to be working ok in release 2.0. I was using 0.12.1, had the problem, then found this issue when searching for the solution. I upgraded, then all seemed fine.

**Comment by golyalpha** [comment]
@louking Alright, thanks for the info, I'll close, and reopen if it fails for some reason.
